website/views.py
import requests
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Notes, Categories, Expenses
from . import db
import json
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from . import dashboard
import requests
from sqlalchemy import asc, desc

from website import models

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def expenses():
    if request.method == 'POST':
        description = request.form.get('description')
        category = request.form.get('category')
        expensedate = datetime.strptime(request.form.get('expensedate'),'%Y-%m-%d')
        amount = request.form.get('amount')
        submittime = datetime.now()

        if len(description) < 1:
            flash('Description is too short!', category='error')
        else:
            new_expense = Expenses(description=description, category=category, expensedate=expensedate, amount=amount, submittime=submittime, user_id=current_user.id)
            db.session.add(new_expense)
            db.session.commit()
            flash('Expense added!', category='success')

        print(request.form.get('expensedate'))

    # expensesCurrentmonth = dashboard.getTotalSpend_Month(current_user.id)
    # print('Total expense for this month',expensesCurrentmonth)

    # SpendingTrends = dashboard.getSpendingTrends(current_user.id)
    # print('Spending Trends for this month',SpendingTrends)

    # expensesMonthly = dashboard.getTotalMonthlySpend(current_user.id)
    # print('Monthly Spending',expensesMonthly)

    # items = Expenses.query.all()
    items = Expenses.query.order_by(Expenses.expensedate).all()
    dateToday = datetime.now()
    categories = Categories.query.order_by(Categories.name).all()

    return render_template("expense.html", user=current_user, expenses=items, categories=categories, dateToday=dateToday)
    # return render_template("index.html", user=current_user, expenses=items, categories=categories)

@views.route('/delete-expense', methods=['POST'])
def delete_expense():
    expense = json.loads(request.data)
    expenseId = expense['expenseId']
    expense = Expenses.query.get(expenseId)
    print(expenseId)
    if expense:
       db.session.delete(expense)
       db.session.commit()

    return jsonify({})

# This route is for deleting expense
@views.route('/deleteexpense/<id>/', methods = ['GET', 'POST'])
def deleteexpense(id):
    my_data = Expenses.query.get(id)
    db.session.delete(my_data)
    db.session.commit()
    flash("Expense Deleted Successfully")

    return redirect(url_for('views.expenses'))

#this route is for inserting data to y
# database via html forms
@views.route('/insertexpense', methods = ['POST'])
@login_required
def insertexpense():

    if request.method == 'POST':
        description = request.form.get('description')
        category = request.form.get('category')
        expensedate = datetime.strptime(request.form.get('expensedate'),'%Y-%m-%d')
        amount = request.form.get('amount')
        submittime = datetime.now()
        new_expense = Expenses(description=description, category=category, expensedate=expensedate, amount=amount, submittime=submittime, user_id=current_user.id)
        db.session.add(new_expense)
        db.session.commit()

        flash("Expense Inserted Successfully")

        return redirect(url_for('views.expenses'))
        # return render_template("home.html", user=current_user)

#this is our update route where we are going to update our expense
@views.route('/updateexpense', methods = ['GET', 'POST'])
@login_required
def updateexpense():

    if request.method == 'POST':
        my_data = Expenses.query.get(request.form.get('id'))
        my_data.description = request.form.get('description')
        my_data.category = request.form.get('category')
        my_data.expensedate = datetime.strptime(request.form.get('expensedate'),'%Y-%m-%d')
        my_data.amount = request.form.get('amount')
        my_data.submittime = datetime.now()
        print(my_data)
        db.session.commit()
        flash("Expense Updated Successfully")

        return redirect(url_for('views.expenses'))


@views.route('/notes', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Notes(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Notes.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@views.route('/categories', methods=['GET', 'POST'])
@login_required
def categories():
    if request.method == 'POST':
        items = Categories.query.all()
        categoryname = request.form.get('category').strip()
        if not categoryname in map(lambda x: x.name,items):
            if len(categoryname) < 1:
                flash('category is too short!', category='error')
            else:
                new_category = Categories(name=categoryname)
                db.session.add(new_category)
                db.session.commit()
                flash('Category added!', category='success')
        else:
            flash('Exist', category='error')
    items = Categories.query.order_by(Categories.name).all()
    return render_template("category.html", user=current_user, categories=items)

@views.route('/delete-category', methods=['POST'])
def delete_category():
    category = json.loads(request.data)
    categoryId = category['categoryId']
    category = Categories.query.get(categoryId)
    if category:
       db.session.delete(category)
       db.session.commit()

    return jsonify({})

@views.route('/reports', methods=['GET'])
@login_required
def reports():
    expensesCurrentmonth = dashboard.getTotalSpend_Month(current_user.id)
    print('Total expense for this month',expensesCurrentmonth)

    SpendingTrends = dashboard.getSpendingTrends(current_user.id)
    print('Spending Trends for this month',SpendingTrends)

    expensesMonthly = dashboard.getTotalMonthlySpend(current_user.id)

    href = 'http://127.0.0.1:5000/api/v1/expense/monthly'
    params = {
    'type': 'monthly',
    'userid': 1,
    }
    # return requests.get('http://example.com').content
    # expensesMonthly = requests.get('http://127.0.0.1:5000/api/v1/expense/monthly')
    expensesMonthlyJson = dashboard.getTotalMonthlySpendJson(current_user.id)

    js=json.loads(expensesMonthlyJson)
    print('Test 1 - Monthly Spending',expensesMonthly)
    print('Test 2 - Monthly Spending Json', js)   # Jinja parses json with single quote!!!
    print('Test 3 - Monthly Spending Json', expensesMonthlyJson) # Jinja uunable to parse json with double quote!!!


    return render_template("reports.html", user=current_user, expensesMonthly=js, expensesMonthlyJson=js)

@views.route('/api/v1/expense/monthly', methods=['GET'])
def api_monthly():
    # http://127.0.0.1:5000/api/v1/expense/monthly
    type = request.args.get('type')
    # expensesCurrentmonth = dashboard.getTotalMonthlySpend(current_user.id)
    expensesCurrentmonth = dashboard.getTotalMonthlySpendJson(1)
    print(expensesCurrentmonth)
    return expensesCurrentmonth

@views.route('/api/v1/expense/monthly/all', methods=['GET'])
def api_monthlyTotal_all():
    # http://127.0.0.1:5000/api/v1/expense/monthly/all
    expensesCurrentmonth = dashboard.getTotalSpend_Month(current_user.id)
    return jsonify(expensesCurrentmonth)

@views.route('/api/v1/expense/monthly/trend', methods=['GET'])
def api_monthlyTotal_trend():
    # http://127.0.0.1:5000/api/v1/expense/monthly/trend
    expensesCurrentmonth = dashboard.getSpendingTrends(current_user.id)
    return jsonify(expensesCurrentmonth)


# Examples of API query ------------------------------------------------------------------

@views.route('/query-example', methods=['GET'])
def query_example():
    # http://127.0.0.1:5000/query-example?language=Python
    # http://127.0.0.1:5000/query-example?language=Python&framework=Flask&website=DigitalOcean
    # if key doesn't exist, returns None
    language = request.args.get('language')

    # if key doesn't exist, returns a 400, bad request error
    framework = request.args['framework']

    # if key doesn't exist, returns None
    website = request.args.get('website')

    return '''
              <h1>The language value is: {}</h1>
              <h1>The framework value is: {}</h1>
              <h1>The website value is: {}'''.format(language, framework, website)


# GET requests will be blocked
"""
    {
        "language" : "Python",
        "framework" : "Flask",
        "website" : "Scotch",
        "version_info" : {
            "python" : "3.9.0",
            "flask" : "1.1.2"
        },
        "examples" : ["query", "form", "json"],
        "boolean_test" : true
    }
"""
@views.route('/json-example', methods=['POST'])
def json_example():
    request_data = request.get_json()

    language = None
    framework = None
    python_version = None
    example = None
    boolean_test = None

    if request_data:
        if 'language' in request_data:
            language = request_data['language']

        if 'framework' in request_data:
            framework = request_data['framework']

        if 'version_info' in request_data:
            if 'python' in request_data['version_info']:
                python_version = request_data['version_info']['python']

        if 'examples' in request_data:

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Expense</a>
          <a class="nav-item nav-link" id="home" href="/categories">Categories</a>
          <a class="nav-item nav-link" id="home" href="/reports">Reports</a>
          <!--<a class="nav-item nav-link" id="notes" href="/notes">Notes</a>-->
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/category.html
{% extends "base.html" %} {% block title %}Categories{% endblock %} {% block content%}
<h2>Manage <b>Categories </b></h2>
<ul class="list-group list-group-flush" id="categories">
  {% for category in categories %}
  <li class="list-group-item">
    {{ category.name }}
    <button type="button" class="close" onClick="deleteCategory({{ category.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="category" id="category" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Category</button>
  </div>
</form>
{% endblock %}

website/templates/expense.html
{% extends "base.html" %} {% block title %}Expenses{% endblock %} {% block content%}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
  <link rel="stylesheet" type="text/css"
    href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.16.0/extensions/filter-control/bootstrap-table-filter-control.css">
</head>

<h2>Manage <b>Expenses </b> <button type="button" class="btn btn-success float-right" data-toggle="modal"
    data-target="#mymodal">Add New Expense</button> </h2>

<body>
  <div class="table-responsive">
    <table id="table" data-toggle="table" data-filter-control="true" data-show-search-clear-button="true"
      data-sortable="true" data-pagination="true" class="table table-borderless table-sm table-striped">
      <thead class="thead-dark">
        <tr>
          <!--special characters and spaces not allowed in data-field name-->
          <th data-field="id" data-sortable="true">id</th>
          <th data-field="description" data-filter-control="select" data-sortable="true">Description</th>
          <th data-field="category" data-filter-control="select" data-sortable="true">Category</th>
          <th data-field="expensedate" data-filter-control="input"
            data-filter-datepicker-options='{"autoclose":true, "clearBtn": true, "todayHighlight": true}'
            data-sortable="true">Expense Date</th>
          <th data-field="amount" data-filter-control="select" data-sortable="true">Amount</th>
          <th data-field="submittime" data-filter-control="input" data-sortable="true">Submit Time</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in user.expenses %}
        <tr>
          <!--special characters and spaces not allowed in data-field name-->
          <th>{{ expense.id }}</th>
          <td>{{ expense.description }}</td>
          <td>{{ expense.category }}</td>
          <td>{{ expense.expensedate.strftime('%Y-%m-%d') }}</td>
          <td>{{ "$%.2f"|format(expense.amount) }}</td>
          <td>{{ expense.submittime.strftime('%Y-%m-%d %H:%M:%S') }}</td>
          <td>
            <a href="/updateexpense/{{expense.id}}" class="btn btn-warning btn-xs" data-toggle="modal"
              data-target="#modaledit{{expense.id}}">!</a>
            <a href="/deleteexpense/{{expense.id}}" class="btn btn-danger btn-xs"
              onclick="return confirm('Confirm delete?')">&times;</a>
          </td>
        </tr>

        <!-- Modal Edit Expense -->
        <div id="modaledit{{expense.id}}" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Update Expense</h4>
              </div>
              <div class="modal-body">
                <form action="{{ url_for('views.updateexpense') }}" method="POST">
                  <!-- <div class="form-group"> -->
                  <!-- <label>ID:</label> -->
                  <input type="hidden" name="id" value="{{expense.id}}">
                  <!-- <input type="hidden" class="form-control" name="idx" value="{{expense.id}}"> -->
                  <!-- </div> -->
                  <div class="form-group">
                    <label>Description:</label>
                    <input type="text" class="form-control" name="description" value="{{expense.description}}">
                  </div>
                  <div class="form-group">
                    <label>Category:</label>
                    <!--input type="text" class="form-control" name="category" required="1"-->
                    <select class="custom-select" name="category" size="1" required="1" value="{{expense.category}}">
                      <!-- <option selected disabled>Open this select menu</option> -->
                      {% for category in categories %}
                      <option value="{{ category.name }}">{{ category.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <!--<div class="form-group">
                          <label>Category:</label>
                          <input type="text" class="form-control" name="category" value="{{expense.category}}">
                      </div>-->
                  <div class="form-group">
                    <label>Expense Date:</label>
                    <input type="date" class="form-control" name="expensedate"
                      value="{{ expense.expensedate.strftime('%Y-%m-%d') }}">
                  </div>
                  <div class="form-group">
                    <label>Amount:</label>
                    <input type="number" step=0.01 min="0" max="9999999" class="form-control" name="amount" value="{{expense.amount}}">
                  </div>
                  <div class="form-group">
                    <button class="btn btn-primary" type="submit">Update</button>
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
  <script
    src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap DatePicker -->
    <script type="text/javascript">
      $(function () {
          $('#txtDate').datepicker({
              format: "dd/mm/yyyy"
          });
      });
  </script>
</body>

<!-- Modal Add Expense -->
<div id="mymodal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add Expense</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('views.insertexpense') }}" method="POST">
          <div class="form-group">
            <label>Description:</label>
            <input type="text" class="form-control" name="description" required="1">
          </div>
          <div class="form-group">
            <label>Category:</label>
            <!--input type="text" class="form-control" name="category" required="1"-->
            <select class="form-control" name="category" size="1" required="1">
              <!-- <option selected disabled>Open this select menu</option> -->
              {% for category in categories %}
              <option value="{{ category.name }}">{{ category.name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label>Expense Date:</label>
            <input type="date" class="form-control" name="expensedate" required="1"
              value="{{ dateToday.strftime('%Y-%m-%d') }}">
          </div>
          <div class="form-group">
            <label>Amount:</label>
            <input type="number" step=0.01 min="0" max="9999999" class="form-control" name="amount" required="1">
          </div>
          <div class="form-group">
            <button class="btn btn-primary" type="submit">Add Expense</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/index.html
{% extends "base.html" %} {% block title %}Expenses{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Manage <b>Expenses </b> <button type="button" class="btn btn-success float-right"
                        data-toggle="modal" data-target="#mymodal">Add New Expense</button> </h2>
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Description</th>
                        <th>Category</th>
                        <th>Expense Date</th>
                        <th>Amount</th>
                        <th>Submitted Date</th>
                        <th>Action</th>
                    </tr>
                    {% for row in user.expenses %}
                    <tr>
                        <th>{{ row.id }}</th>
                        <td>{{ row.description }}</td>
                        <td>{{ row.category }}</td>
                        <td>{{ row.expensedate.strftime('%Y-%m-%d') }}</td>
                        <td>{{ "$%.2f"|format(row.amount) }}</td>
                        <td>{{ row.submittime.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                        <td>
                            <a href="/updateexpense/{{row.id}}" class="btn btn-warning btn-xs" data-toggle="modal"
                                data-target="#modaledit{{row.id}}">Edit</a>
                            <a href="/deleteexpense/{{row.id}}" class="btn btn-danger btn-xs"
                                onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                        </td>
                    </tr>

                    <!-- Modal Edit Expense -->
                    <div id="modaledit{{row.id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Update Information</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{ url_for('views.updateexpense') }}" method="POST">
                                        <!-- <div class="form-group"> -->
                                        <!-- <label>ID:</label> -->
                                        <input type="hidden" name="id" value="{{row.id}}">
                                        <!-- <input type="hidden" class="form-control" name="idx" value="{{row.id}}"> -->
                                        <!-- </div> -->
                                        <div class="form-group">
                                            <label>Description:</label>
                                            <input type="text" class="form-control" name="description"
                                                value="{{row.description}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Category:</label>
                                            <!--input type="text" class="form-control" name="category" required="1"-->
                                            <select class="custom-select" name="category" size="1" required="1"
                                                value="{{row.category}}">
                                                <!-- <option selected disabled>Open this select menu</option> -->
                                                {% for category in categories %}
                                                <option value="{{ category.name }}">{{ category.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <!--<div class="form-group">
                                    <label>Category:</label>
                                    <input type="text" class="form-control" name="category" value="{{row.category}}">
                                </div>-->
                                        <div class="form-group">
                                            <label>Expense Date:</label>
                                            <input type="date" class="form-control" name="expensedate"
                                                value="{{ row.expensedate.strftime('%Y-%m-%d') }}">
                                        </div>
                                        <div class="form-group">
                                            <label>Amount:</label>
                                            <input type="number" step=0.01 class="form-control" name="amount"
                                                value="{{row.amount}}">
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-primary" type="submit">Update</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </table>
            </div>
            <!-- Modal Add Expense -->
            <div id="mymodal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Add Expense</h4>
                        </div>
                        <div class="modal-body">
                            <form action="{{ url_for('views.insertexpense') }}" method="POST">
                                <div class="form-group">
                                    <label>Description:</label>
                                    <input type="text" class="form-control" name="description" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Category:</label>
                                    <!--input type="text" class="form-control" name="category" required="1"-->
                                    <select class="form-control" name="category" size="1" required="1">
                                        <!-- <option selected disabled>Open this select menu</option> -->
                                        {% for category in categories %}
                                        <option value="{{ category.name }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Expense Date:</label>
                                    <input type="date" class="form-control" name="expensedate" required="1"
                                    value="{{ dateToday.strftime('%Y-%m-%d') }}">
                                </div>
                                <div class="form-group">
                                    <label>Amount:</label>
                                    <input type="number" step=0.01 class="form-control" name="amount" required="1">
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Add Expense</button>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}